// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu6b0JM_aIXENkvBQ12OkyYgankT3zRos',
    appId: '1:453967694540:web:3456d36c181586fafd5069',
    messagingSenderId: '453967694540',
    projectId: 'chat-app-bf41e',
    authDomain: 'chat-app-bf41e.firebaseapp.com',
    storageBucket: 'chat-app-bf41e.firebasestorage.app',
    measurementId: 'G-7F63VV05T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqZRB4CV0mjTh09mm30Z3zuZxyFdG9xPI',
    appId: '1:453967694540:android:47c67c1a6ffd61d9fd5069',
    messagingSenderId: '453967694540',
    projectId: 'chat-app-bf41e',
    storageBucket: 'chat-app-bf41e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAszyZpOi0ZqQFDT0XdSJUxb0uutxqS4Ho',
    appId: '1:453967694540:ios:d1bb410d4155ffb8fd5069',
    messagingSenderId: '453967694540',
    projectId: 'chat-app-bf41e',
    storageBucket: 'chat-app-bf41e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAszyZpOi0ZqQFDT0XdSJUxb0uutxqS4Ho',
    appId: '1:453967694540:ios:d1bb410d4155ffb8fd5069',
    messagingSenderId: '453967694540',
    projectId: 'chat-app-bf41e',
    storageBucket: 'chat-app-bf41e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu6b0JM_aIXENkvBQ12OkyYgankT3zRos',
    appId: '1:453967694540:web:b731e017ab864bc9fd5069',
    messagingSenderId: '453967694540',
    projectId: 'chat-app-bf41e',
    authDomain: 'chat-app-bf41e.firebaseapp.com',
    storageBucket: 'chat-app-bf41e.firebasestorage.app',
    measurementId: 'G-E7CR340QVF',
  );
}
